name: Python Matrix Demo

on:
<<<<<<< HEAD
  workflow_dispatch:
=======
  workflow_dispatch: 
>>>>>>> 585d2215cc9817c22f782f82033c720419fcd8c9

jobs:
  say-hello:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python version
        run: python --version

      - name: Echo Hello
        run: echo "hello from Python ${{ matrix.python-version }}"
